### PR TITLE
IntorPro: Split modulesfor for  related scala version 

### PR DESCRIPTION
**Pull request by smaryn**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

Please review
https://github.com/deeplearning4j/deeplearning4j/blob/master/CONTRIBUTING.md before opening a pull request.

### CODE REVIEW

**Comment by saudet** [comment]
The build should work exactly the same way using `change-scala-versions.sh` as with nd4j, deeplearning4j, etc. Are you having issues using that script in the pipeline only for this project?

**Comment by smaryn** [comment]
Sure you can use  `change-scala-versions.sh` without applying changes on current pull request.
Main reason of request, is to show up how should be organized Maven project for storing multiple modules with dependencies on same sources,
We suppose there will be following Benefits: 
- You can start to use Maven according to best practice with Maven release plugin, saving version semantic, tagging from maven, apply all maven features.
- Saving structure according to Maven documentation - you can be more flexible with during to bring new Maven plugins.
- Current approach should make future migration, if it have place (gradle, sbt), more painless.
- Release process will exclude supporting of shell scripts and their usage, by keeping actions Build/Compile on Maven side.
- Release and Development process become more clear

**Comment by saudet** [comment]
Yes, I also think we should do that for all the repositories, but we can start with ScalNet, that's a good idea.

@huitseeker What do think of those changes? Please review and merge if it's OK with you.

**Comment by saudet** [comment]
@huitseeker So it's your opinion that we are better off with `change-scala-versions.sh` scripts and such?

**Comment by huitseeker** [comment]
I'm 100% convinced we are better off with something that does not require maintaining two poms. For now that's change-scala-versions — note that's the way every maven project that deals with multiple Scala versions does it. But I'm very open to hearing about other solutions, including :
- having two branches, one for 2.10, a fork of the main one (2.11) to which we backport
- switching to sbt, which knows how to handles this well.
- switching to gradel, which knows how to handle this better.

**Comment by ztaoo** [comment]
@huitseeker , ScalNet is for the scala user.
So, I think switching to sbt is a good choice.

**Comment by saudet** [comment]
@ztaoo Agreed, a pull request for that would be great!

**Comment by ztaoo** [comment]
@saudet 
I have tried to make some contribution to this repos( issue #29), but failed.
Maybe i will try again some day, but not for sure.

**Pull request closed without merging**
