### PR TITLE
Scala Match Error repair

### PR DESCRIPTION
**Pull request by taisenki**
## IrisCSVExample will throw scala match error

SDG.nesterov is false and Model.scala buildModelConfig method will throw a scala match error

### CODE REVIEW

**Comment by maxpumperla** [comment]
@taisenki thanks for this fix. We should take our time to fix the root cause as well, i.e. get rid of the match error. Nesterov = false should be supported as well.

Do you think you could have a look at this? If not, I could help later on.

**Comment by taisenki** [comment]
#@maxpumperla That's simple to dual with the root, but I'm not sure why someone do this change, because 5 versions before that's right.

**Comment by maxpumperla** [comment]
@taisenki I don't quite understand what you're saying ("dual with the root"?), but the idea was to use pattern matching _instead of_ if-else clauses for this, as it's more in flavour of Scala. What we need to do is to add a default case to catch when nesterov is false.

**Comment by taisenki** [comment]
@maxpumperla  I think the two - level iterative pattern matching here is not necessary，but maybe you're right 。

**Comment by maxpumperla** [comment]
@taisenki why did you close this? Sorry, I didn't mean to discourage you. I'm very interested in a fix for this.

**Pull request closed without merging**
